# Generated by Django 5.2.1 on 2025-07-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_en_ligne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etat',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
