# Generated by Django 5.2.4 on 2025-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('entree', 'Entrée'), ('plat_resistant', 'Plat résistant'), ('dessert', 'Dessert')], default='plat_resistant', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('est_epuise', models.BooleanField(default=False)),
                ('est_specialite', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
            ],
        ),
    ]
