# Generated by Django 5.2.1 on 2025-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_cours', max_length=20),
        ),
    ]
