# Generated by Django 5.2.1 on 2025-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commande', '0002_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('livree', 'Livrée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('livree', 'Livrée')], default='en_cours', max_length=20),
        ),
    ]
