# Generated by Django 5.2.1 on 2025-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur')], default='client', max_length=20),
        ),
    ]
