# Generated by Django 5.2.1 on 2025-07-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
